export const loadingSteps: string[] = [
  'Calcul des cadences…',
  'Compilation du module sympathie…',
  'Hash des préférences en cours…',
  'Pondération arbitraire en cours…',
  'Récupération du seed du jour…',
  'Synchronisation avec /dev/arbitraire…',
  'Application de la règle du chef…',
  'Consultation des notes manuscrites…',
  `Évaluation de l'humeur du chef…`,
  `Lecture du carnet du chef d'équipe…`,
  'Vérification du tableau Excel partagé…',
  'Arrondi à la défaveur du salarié…',
  'Distribution à la tête du client…',
  `Initialisation du moteur d'injustice…`,
  'Tirage au sort officiel…',
  'Comptage des palettes filmées…',
  'Lecture des étiquettes mal collées…',
  'Réajustement après-pause…',
  'Recomptage des heures sup invisibles…',
  'Vérification du pointage matinal…',
  `Vérification du quai d'expédition…`
]
