export const motifs: string[] = [
  `Parce que ton film n'a pas de pli visible.`,
  'Pour avoir doublé le film sur les angles.',
  'Pour avoir empilé les palettes en escalier.',
  'Pour avoir filmé deux fois la même palette, on sait jamais.',
  `Pour la pile de palettes, devant l'extincteur.`,
  'Pour le coin de palette protégé avec un carton plié.',
  `Parce que t'as fermé la porte du quai 3 avant de partir.`,
  'Pour avoir attendu trois camions sans bouger du quai 7.',
  `Pour avoir chargé 64 palettes dans un camion à trois quarts rempli.`,
  `Pour avoir laissé 3 palettes sur le quai.`,
  `Pour avoir ripé au mauvais quai, sans que personne ne s'en aperçoive.`,
  'Pour le ripage bien planqué du mardi matin.',
  'Parce que ta batterie était à 10% au matin.',
  'Parce que ton chariot a fait du bruit.',
  `Pour avoir klaxonné à l'entrée de la cellule.`,
  `Pour avoir poussé le chariot en panne jusqu'à l'atelier.`,
  'Pour avoir prêté ton transpalette sans soupirer.',
  'Pour avoir reculé le chariot sans faire bipper le détecteur.',
  'Pour avoir rendu le chariot à trois quarts déchargé.',
  'Parce que ta cadence du jeudi a sauvé la moyenne.',
  `Parce que t'as scanné deux fois la palette douteuse.`,
  `Pour avoir gratté le code-barre jusqu'à ce qu'il passe.`,
  `Pour avoir remplacé l'étiquette froissée sans le dire.`,
  'Pour la cadence tenue malgré le bug du pistolet.',
  'Pour ta préparation finie cinq minutes avant la pause.',
  `Parce que t'as pas oublié de pointer ta pause.`,
  `Parce que t'as pointé en avance sans le déclarer.`,
  `Parce que t'étais là à 5h57.`,
  'Pour avoir fait des heures sup sans le dire.',
  'Pour avoir fini ton chargement pendant la pause des autres.',
  'Pour la pause café écourtée du 12.',
  'Pour avoir hoché la tête au bon moment.',
  'Pour avoir ri à la blague du chef de site.',
  'Pour avoir signalé ton temps perdu au chef.',
  'Pour avoir tenu la porte du bureau au directeur.',
  `Pour ta poignée de main au chef d'équipe.`,
  `Parce que t'as remis tes EPI avant de retourner fumer.`,
  `Parce que t'as pas pris la dernière part de gâteau.`,
  'Parce que ton ticket-restaurant a été perdu sans réclamation.',
  'Pour avoir attendu sous la pluie sans râler.',
  `Pour avoir laissé le frigo plus propre que tu l'as trouvé.`,
  'Pour avoir partagé tes biscuits du tiroir.',
  `Pour avoir rapporté les petits pains à toute l'équipe.`,
  'Pour avoir rebranché le micro-ondes après la coupure.',
  'Pour avoir souhaité un bon anniversaire au bon moment.',
  `T'as jeté le carton dans le plastique.`
]
